version: '2'

services:
 rabbitmq:
   image: rabbitmq:3.6.14-management
   container_name: rabbitmq
   restart: always
   volumes:
      - /Users/mark/dockerMapPath/rabbitmq:/var/lib/rabbitmq
      - /Users/mark/dockerMapPath/rabbitmq/config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
   environment:
     - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
   dns:
     - 8.8.8.8
   ports:
     - "5672:5672"
     - "15672:15672" 
   
