version: '2'

services:  
  mynginx:
    image: nginx:1.16.0
    container_name: mynginx
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=mark-nginx
      - NGINX_PORT=80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /Users/mark/gitworkspace/fin-web/dist:/usr/share/nginx/html
    mem_limit: 256m

  fin-autotest:
    image: fin-autotest:lastest
    container_name: fin-autotest
    restart: always
    ports:
      - "9098:8080"
    mem_limit: 2g
  