version: '2'

services:
  
  rabbitmq:
    image: rabbitmq:3.6.14-management
    container_name: rabbitmq
    # restart: always
    network_mode: "bridge"
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    ports:
      - 5672:5672
      - 15672:15672
    mem_limit: 512m
    
  api-admin:
    container_name: api-admin
    image: api-admin:lastest
    ports:
      - 8081:8080
    # restart: always
    mem_limit: 1g
  
  mongo:
    container_name: mongo
    image: mongo:3.6
    volumes:
      - /Users/mark/dockerMapPath/mongo:/data/
    ports:
      - 27017:27017
    # restart: always
    mem_limit: 1g
  
  mysql56:
    image: mysql:5.6.35
    container_name: mysql56
    # restart: always
    network_mode: "bridge"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    ports:
      - 3307:3306
    volumes:
      - /Users/mark/dockerMapPath/mysql:/var/lib/mysql
    mem_limit: 1g
  
  rancher-server:
    image: rancher/server
    container_name: rancher-server
    hostname: rancher-server
    # restart: always
    network_mode: "bridge"
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    ports:
      - 8999:8080
    mem_limit: 2g
  
  elasticsearch:
    image: itzg/elasticsearch:5.5
    container_name: elasticsearch5
    hostname: elasticsearch
    network_mode: "bridge"
    privileged: true
    # restart: always
    volumes:
      - /Users/mark/dockerMapPath/elk/elasticsearch/config:/data
      - /Users/mark/dockerMapPath/elk/elasticsearch/data:/conf
    dns:
      - 8.8.8.8
    ports:
      - "9200:9200"
      - "9300:9300"
    
  kibana:
    image: kibana:5.5
    container_name: kibana5 
    # restart: always
    network_mode: "bridge"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    dns:
      - 8.8.8.8
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  zoo1:
    image: zookeeper:3.4
    # restart: always
    container_name: zookeeper1
    hostname: zoo1
    ports:
      - 2181:2181
    dns:
      - 8.8.8.8
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo2:
    image: zookeeper:3.4
    # restart: always
    container_name: zookeeper2
    hostname: zoo2
    ports:
      - 2182:2181
    dns:
      - 8.8.8.8
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
  zoo3:
    image: zookeeper:3.4
    # restart: always
    container_name: zookeeper3
    hostname: zoo3
    ports:
      - 2183:2181
    dns:
      - 8.8.8.8
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888