version: '2'

services:
  
  sonarqube-server:
    image: sonarqube:7.9-community
    container_name: sonarqube-server
    hostname: sonarqube-server
    # sudorestart: always
    network_mode: "bridge"
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    ports:
      - 9000:9000
    mem_limit: 2g
    