version: '2'

services:
  
  traefik:
    container_name: traefik
    image: traefik:v2.0
    restart: always
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8081:8080
    mem_limit: 512m
    
  whoami:
    container_name: whoami
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker`)"
    mem_limit: 512m
  