version: '2'

services:
  
  traefik:
    container_name: traefik2
    image: traefik:v2.0
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8081:8080
    mem_limit: 512m
    
  whoami:
    container_name: test
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`docker.localhost`)"
    mem_limit: 512m
  