################################################################
# API and dashboard configuration
################################################################
[api]
################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[providers.docker]
watch = true

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.web]
    address = ":80"

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

################################################################
# Access logs configuration
################################################################
[log]

# Log level
#
# Optional
# Default: "ERROR"
#
level = "info"

# Optional
#
[accessLog]
