version: '2'
# 基础服务
services:  
  mynginx:
    image: nginx:latest
    container_name: mynginx
    network_mode: "bridge"
    restart: always
    ports:
      - "1180:80"
    environment:
      - NGINX_HOST=mark-nginx
      - NGINX_PORT=80
    volumes:
      - /Users/mark/dockerMapPath/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /Users/mark/dockerMapPath/nginx/www:/usr/share/nginx/html
    mem_limit: 512m

  ftp-server:
    image: stilliard/pure-ftpd
    container_name: ftp-server
    network_mode: "bridge"
    # restart: always
    ports:
      - "21:21"
      - 30000-30009:30000-30009
    environment:
      - PUBLICHOST=localhost
    volumes:
      - /Users/mark/dockerMapPath/ftpserver/passwd:/etc/pure-ftpd/passwd
      - /Users/mark/dockerMapPath/ftpserver/data:/home/ftpusers
    mem_limit: 256m
  