version: '2'

services:  
  elasticsearch:
    image: itzg/elasticsearch:5.5
    container_name: elasticsearch5
    hostname: elasticsearch
    network_mode: "bridge"
    privileged: true
    restart: always
    volumes:
      - /Users/mark/dockerMapPath/elk/elasticsearch/config:/data
      - /Users/mark/dockerMapPath/elk/elasticsearch/data:/conf
    dns:
      - 8.8.8.8
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"
    
  kibana:
    image: kibana:5.5
    container_name: kibana5 
    restart: always
    network_mode: "bridge"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    dns:
      - 8.8.8.8
    links:
      - elasticsearch
    depends_on:
      - elasticsearch