version: '2'

services:
  kong:
    image: kong:1.2.1
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=root
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN='0.0.0.0:8001'
    command : kong docker-start
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    links: 
      - kong-database

  kong-dashboard:
    image: pgbi/kong-dashboard:v2
    ports:
      - "8082:8080"
    links: 
      - kong
    depends_on:
      - kong

  kong-database:
    image: postgres:9.5
    hostname: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - KONG_PG_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    