version: '2'

services:
  # sql检查工具
  centos_inception:
    image: centos_inception:v1
    container_name: centos_inception
    # volumes:
    #   - /Users/bitmain/githubWorkspace/Yearning/install/opt/inc.cnf:/opt/inception/bin/inc.cnf
    restart: always
    ports:
      - "6669:6669"
  # yearning sql审核平台
  db:
    image: mysql:5.7
    volumes:
      - ./docker/etc/mysql/:/etc/mysql/conf.d/
      - ./db_data/:/var/lib/mysql/
      - ./init-sql/:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yearning
      MYSQL_DATABASE: Yearning
      MYSQL_USER: yearning
      MYSQL_PASSWORD: yearning
  yearning:
    image: registry.cn-hangzhou.aliyuncs.com/cookie/yearning:v1.3.3
    depends_on:
      - db
    ports:
      - "8080:80"
      - "8000:8000"
    environment:
      HOST: localhost
      MYSQL_PASSWORD: yearning
      MYSQL_USER: root
      MYSQL_ADDR: db

# 默认账号：admin，默认密码：Yearning_admin
# 感谢 eacdy 张功震 贡献