version: '2'
# sudo docker run --name gopub -e MYSQL_HOST=x.x.x.x -e MYSQL_PORT=3306  -e MYSQL_USER=root -e MYSQL_PASS=123456 -e MYSQL_DB=walle -p 8192:8192  --restart always  -d   lc13579443/gopub:latest
services:
 gopub:
   image: lc13579443/gopub:latest
   container_name: gopub
   restart: always
   environment:
     - MYSQL_HOST=root
     - MYSQL_PASS=root
     - MYSQL_PORT=3307
     - MYSQL_DB=walle
     - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
   ports:
     - 8192:8192
   volumes:
     - /Users/mark/dockerMapPath/gopub:/var/lib/mysql
